[package]
name = "discord-irc"
version = "0.1.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
configc = { version = "0.10.1", package = "config" }
env_logger = "0.7.1"
encoding = "0.2.33"
failure = "0.1.6"
futures = "0.3.1"
log = "0.4.8"
serde = "1.0.104"
yaircc = "0.1.0"
async-std = "1.4.0"
surf = "1.0.3"

[dependencies.serenity]
version = "0.7.4"
default-features = false
features = [
    "cache",
    "client",
    "model",
    "rustls_backend",
    "utils",
]
