[package]
name = "discord-irc"
version = "0.1.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
configc = { version = "0.9.3", package = "config" }
env_logger = "0.6.1"
encoding = "0.2.33"
failure = "0.1.5"
futures-preview = { version = "0.3.0-alpha.16", features = ["io-compat"] }
lazy_static = "1.3.0"
log = "0.4.6"
rustls = "0.15.2"
serde = "1.0.92"
yaircc = "0.0.0"
tokio = "0.1.21"

[dependencies.serenity]
version = "0.6.0-rc.2"
default-features = false
features = [
    "client",
    "rustls_backend",
]

[dependencies.reqwest]
version = "0.9.18"
default-features = false
features = [
    "rustls-tls",
]
